name: eli_archgirl
favicon: null
layout_spectrum: 0.33807
typography_spectrum: 0.58118
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#352d2a'
    - '#ebeef5'
    - '#8d888c'
    - '#fd9026'
    - '#a63b17'
  brandStrength: 0.5625
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
